openapi: 3.0.0
info:
  version: "1.0.0"
  title: API Rest DoH
  description: Documentación de la API de DNS on Https

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /custom-domains:
    get:
      operationId: "api.dns.obtener_custom_domains"
      tags:
        - "Custom Domains"
      summary: "Listado de dominios custom"
      description: "Obtiene la lista de todos los custom domains registrados"
      parameters:
        - in: query
          name: q
          required: false
          schema:
            type: string
            example: localhost
          description: El dominio del registro a buscar
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
    post:
      operationId: "api.dns.crear"
      tags:
        - "Custom Domains"
      summary: "Alta de un custom domain"
      description: "Crea un nuevo custom domain y lo agrega a la lista de custom domains"
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se cargo el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "Dominio o ip duplicado"
  /custom-domains/{domain}:
    put:
      operationId: "api.dns.modificar"
      tags:
        - "Custom Domains"
      summary: "Actualiza custom domain"
      description: "Actualiza la informacion de un dominio custom del DoH"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El dominio del registro a borrar
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        200:
          description: "Se cargo el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Domain not found"
    delete:
      operationId: "api.dns.borrar"
      tags:
        - "Custom Domains"
      summary: "Borrar custom domain"
      description: "Borra un dominio custom del DoH"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El dominio del registro a borrar
      responses:
        200:
          description: "Operación de borrado exitosa"
        404:
          description: "Dominio no encontrado"
  /domains/{domain}:
    get:
      operationId: "api.dns.obtener_dominio"
      tags:
        - "Domains"
      summary: "Busqueda dominio"
      description: "Obtiene la ip asociada a un dominio"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
            example: 'www.fi.uba.ar' 
          description: El dominio para el cual se quiere averiguar la ip
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"
# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
        mensaje:
          type: "string"
