openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de Alumnos
  description: Documentación de la API de Alumnos de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /custom-domains:
    get:
      operationId: "api.dns.obtener_custom_domains"
      tags:
        - "Custom Domains"
      summary: "Listado de dominios custom"
      description: "Obtiene la lista de todos los custom domains registrados"
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
    post:
      operationId: "api.dns.crear"
      tags:
        - "Custom Domains"
      summary: "Alta de un custom domain"
      description: "Crea un nuevo custom domain y lo agrega a la lista de custom domains"
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputDomain'
      responses:
        201:
          description: "Se cargo el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "Dominio o ip duplicado"
  /alumnos/{id_alumno}:
    get:
      operationId: "api.alumnos.obtener_uno"
      tags:
        - "Alumnos"
      summary: "Alumno de la materia"
      description: "Obtiene un alumno particular de la materia"
      parameters:
        - in: path
          name: id_alumno
          required: true
          schema:
            type: integer
          description: El id del usuario a obtener
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Alumno no encontrado"
    delete:
      operationId: "api.alumnos.borrar"
      tags:
        - "Alumnos"
      summary: "Borrar alumno de la materia"
      description: "Borra un alumno de la materia"
      parameters:
        - in: path
          name: id_alumno
          required: true
          schema:
            type: integer
          description: El id del usuario a borrar
      responses:
        204:
          description: "Operación de lectura exitosa"
        404:
          description: "Alumno no encontrado"
# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
        mensaje:
          type: "string"
